### ISSUE TITLE
Question Related to Motion Blur Setting

### ISSUE THREAD

**Issue by VaporeonScripts** [jbritain/Ebin-Shaders-Resurrected#3]
**Describe the bug**
Not really a bug but a question, while i use motion blur and i move, both my hands look blurry/bad (ik its motion blur but id like to know if there was any way to disable that)
**Screenshots**
**Minecraft Version/Mods (please complete the following information):**
 - Minecraft Version: 1.21
 - Shaders mod : iris latest
 - Other mods: too many but not related lol
**Specifications (please complete the following information):**
Garuda Linux
rx 6750xt
![image](https://github.com/jbritain/Ebin-Shaders-Resurrected/assets/133986238/d3178b6d-423a-4c38-bbc4-25b8c322afde)

**Comment by VaporeonScripts** [comment]
also, torch hand lighting doesnt work on left hand!

**Comment by jbritain** [comment]
Hi, the torch hand lighting is a known issue, I'm working on it! As for the motion blur, that code is very old and wasn't written by me. I need to have a look into it at some point because I'm not happy with it in general, but it should be reasonably easy to not apply motion blur to the player's hand.

**Comment by jbritain** [comment]
Hand light fixed in 5f25f013bc082f4750f296cc2bec97173a45fc0d

**Comment by jbritain** [comment]
So, 997c50a73ce79e38eed374c709b1e304251dffc0 *improves* the motion blur - the code which prevents motion blur on the hand stopped working at some point. The downside is that some blur still shows up around the hand. Due to the nature of how Ebin's motion blur works, there's not much I can do about that without restructuring things somewhat. I'll consider revisiting this in future but will close this as resolved.
